# Data Encryption and Decryption

# Data Encryption 
            Encryption is a security method in which information is encoded  in such a way that only authorized user can read it .It uses encryptio algorithm to generate chipher text that can only be read if decrypted 
# Data Decryption
            Decryption is the process of taking encoded or encrypted text and convertinf it back into text that you or the computer can read and understand

In [ ]:
# Function to generate key for encryption 
keypath= 'datafiles/key.txt'
def generatekey(keypath):
    with open(keypath,'w') as f:
        for i in range(1,10):
            if i<6:
                f.write(str(i)+' '+(str(i+4))+'\n')
            else:
                f.write(str(i)+' '+(str(i-6))+'\n')
    return 
generatekey(keypath)

In [ ]:
# Function to decrypt a DataFile
keyfile = 'DataFiles/key.txt'
def dictionarykeyFile(keyfile):
    key={}
    with open(keyfile, 'r') as f:
        for line in f:
            line =line.split()
            key[line[0]] = line[1]
    return key
def enctyptMarksData(datafile, keyfile):
    # construct a dictionary for key data
    key=dictionarykeyFile(keyfile)
    with open(datafile, 'r') as f:
        filedata = f.read().split('\n')
    with open('DataFiles/encryptedMarks.txt', 'w') as f:
        for mark in filedata:
            line = ''
            for n in mark:
                line +=key[n]
            f.write(line+'\n')

In [ ]:
 # Function to decrypt a encrypted a File
def decryptMarksData(encryptedfile, keyfile):
    key = dictionarykeyFile(keyfile)
    newkey = {}
    for key, value in key.items():
        newkey[value] = key
    with open(encryptedfile, 'r') as f:
        encrypteddata = f.read().split('\n')
    with open('datafiles/decryptedMarks.txt', 'w') as f:
        for encryptedmark in encrypteddata:
            line = ''
        for n in encryptedmark:
            line +=newkey[n]
            f.write(line + '\n')
    return
encryptedfile = 'datafiles/encryptedMarks.txt'
import timeit
st = timeit.default_timer()
decryptMarksData(encryptedfile, keyfile)
print(timeit,default_timer()-st)

In [ ]:
import numpy as np

In [ ]:
array_id=np.array([1,2,3,4,5,6,7])
print (array_id)
print (type(array_id))

In [ ]:
a=np.arange(15)
print (a)

For example the following code print 1000 numbers in a 1D array

In [ ]:
print (np.arange(1,10+1).reshape(10,1))

In [7]:
import numpy as np
array1=np.random.randint(0,2,size=(3,3))
array1[2][2]
print (array1)
print ('shape',array1.shape)
print ('size',array1.size)
print ('DType',array1.dtype)
print ('data',array1.data)
print ('ItemSize',array1.itemsize)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
shape (3, 3)
size 9
DType int32
data <memory at 0x0000029850FC3990>
ItemSize 4


In [14]:
n=np.ones(15).reshape(3,5)
print (n)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
print (n[::-1])

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
np.ones?

In [31]:
b=[[1,2,3],[2,3,4],[5,6,7]]
b=np.array(b)
print (b)

[[1 2 3]
 [2 3 4]
 [5 6 7]]


In [32]:
b+=1
print (b)

[[2 3 4]
 [3 4 5]
 [6 7 8]]


In [34]:
a=np.arange (1,7).reshape(2,3)
b=np.arange (1,7).reshape(2,3)
print (a)
print (b,'\n')
print (a+b)
print (a/b)


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]] 

[[ 2  4  6]
 [ 8 10 12]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [35]:
a = [1,2,3]
a1 = np.array(a)
print(np.sqrt(a1))
print(np.sin(a1))
print(np.cos(a1))
print(np.log(a1))

[1.         1.41421356 1.73205081]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[0.         0.69314718 1.09861229]
